pages_build_output_dir = "./dist"
name = "luncg-picture-calendar"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "lunch-calendar-worker-photos-bucket"

[[d1_databases]]
binding       = "DB"
database_name = "lunch-calendar"
